url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Justin Lane - Resume

plugins:
  - jekyll-postcss

sass:
  sourcemap: never

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map

# frontmatter

email: justin at justinlane dot org
description: >- # this means to ignore newlines until "baseurl:"
  Justin Lane Resume Elixir React Native Ruby Developer

resume:
  intro_paragraph:  An independent self-starter, who can mentor, train, and coach others, communicate well, and complete work in a timely and efficient manner.
  other_skills: [git, JavaScript, Ruby, React, SQL]